#! /usr/bin/env python

"""
"""

# It imports basic objects.
from untwisted.network import *
from untwisted.utils.stdio import *
from untwisted.utils.shrug import *
from optparse import OptionParser
from libdict import GoogleTranslator

class GServer(object):
    def __init__(self, spin):
        self.translator = GoogleTranslator()
        xmap(spin, ACCEPT, self.handle_accept)
       

    def handle_accept(self, server, client):
        Stdin(client)
        Stdout(client)
        Shrug(client)
        xmap(client, FOUND, self.handle_found)
        xmap(client, CLOSE, lambda client, err: lose(client))

    def handle_found(self, client, data):
        lang_source, lang_target, data = data.split(' ', 2)
        print 'data:', lang_source, lang_target, data
        data = self.translator.translate(data, lang_source, lang_target)
        client.dump('%s\r\n' % data)


if __name__ == '__main__':
    parser   = OptionParser()
    parser.add_option("-p", "--port", dest="port",
                      help='-p port', 
                      metavar="integer", default=5531)
                  
    parser.add_option("-b", "--backlog", dest="backlog",
                      help='-b backlog', 
                      metavar="integer", default=50)

    (opt, args) = parser.parse_args()

    spin = Spin()
    spin.bind(('', int(opt.port)))
    spin.listen(int(opt.backlog))
    Server(spin)

    GServer(spin)
    core.gear.mainloop()







